Fixing a wikipedia.latestRevision() bug :
 >  page.latestRevision()
  File "/home/nico/projets/devpywiki/wikipedia.py", line 839, in latestRevision
    return int(self._permalink)
TypeError: int() argument must be a string or a number, not 'NoneType'

This was happenning when the page was not existing, because we were not raising _getexception when set by getall()


git-svn-id: http://svn.wikimedia.org/svnroot/pywikipedia/trunk@5373 6a7f98fc-eeb0-4dc1-a6e2-c2c589a08aa6